### ISSUE TITLE
cannot install xtb-python using pip

### ISSUE THREAD

**Issue by miroi** [grimme-lab/xtb-python#119]
I cloned xtb-python, installed all dependencies, including intel-mkl and others, 

but still gettin this installation error:
~~~
milias@DESKTOP-7OTLCGO:~/work/software/xtb/xtb-python/.pip install .
Defaulting to user installation because normal site-packages is not writeable
Processing /home/milias/work/software/xtb/xtb-python
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      + meson setup /home/milias/work/software/xtb/xtb-python /home/milias/work/software/xtb/xtb-python/.mesonpy-bdur4b0_ -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/home/milias/work/software/xtb/xtb-python/.mesonpy-bdur4b0_/meson-python-native-file.ini
      The Meson build system
      Version: 1.6.0
      Source dir: /home/milias/work/software/xtb/xtb-python
      Build dir: /home/milias/work/software/xtb/xtb-python/.mesonpy-bdur4b0_
      Build type: native build
      Project name: xtb-python
      Project version: undefined
      C compiler for the host machine: cc (gcc 11.4.0 "cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
      C linker for the host machine: cc ld.bfd 2.38
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      Found pkg-config: YES (/usr/bin/pkg-config) 0.29.2
      Run-time dependency xtb found: YES 6.7.1
      Program python3 (cffi) found: YES (/usr/bin/python3) modules: cffi
      Run-time dependency python found: YES 3.10
      Configuring _libxtb.h with command
      Configuring _libxtb.c with command

      ../meson.build:77:16: ERROR: Command `/usr/bin/python3 /home/milias/work/software/xtb/xtb-python/ffibuilder.py /home/milias/work/software/xtb/xtb-python/.mesonpy-bdur4b0_/_libxtb.h _libxtb` failed with status 1.

      A full log can be found at /home/milias/work/software/xtb/xtb-python/.mesonpy-bdur4b0_/meson-logs/meson-log.txt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
~~~

**Comment by awvwgk** [comment]
For Python 3.12 and newer needs setuptools as a build requirement which is currently not listed in the `pyproject.toml` correctly.

**Comment by miroi** [comment]
Well, I installed seuptools (using pip), python is 3.10.12, but still I am getting this error :

~~~
miroi@MIRO:~/work/software/xtb-python/.pip install -v .
Using pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)
Defaulting to user installation because normal site-packages is not writeable
Processing /home/miroi/work/software/xtb-python
  Running command pip subprocess to install build dependencies
  Collecting meson-python
    Using cached meson_python-0.17.1-py3-none-any.whl (27 kB)
  Collecting cffi
    Using cached cffi-1.17.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (446 kB)
  Collecting pyproject-metadata>=0.7.1
    Using cached pyproject_metadata-0.9.0-py3-none-any.whl (18 kB)
  Collecting packaging>=19.0
    Using cached packaging-24.2-py3-none-any.whl (65 kB)
  Collecting tomli>=1.0.0
    Using cached tomli-2.1.0-py3-none-any.whl (13 kB)
  Collecting meson>=0.63.3
    Using cached meson-1.6.0-py3-none-any.whl (973 kB)
  Collecting pycparser
    Using cached pycparser-2.22-py3-none-any.whl (117 kB)
  Installing collected packages: tomli, pycparser, packaging, meson, pyproject-metadata, cffi, meson-python
  Successfully installed cffi-1.17.1 meson-1.6.0 meson-python-0.17.1 packaging-24.2 pycparser-2.22 pyproject-metadata-0.9.0 tomli-2.1.0
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  Getting requirements to build wheel ... done
  Running command pip subprocess to install backend dependencies
  Collecting patchelf>=0.11.0
    Using cached patchelf-0.17.2.1-py2.py3-none-manylinux_2_5_x86_64.manylinux1_x86_64.musllinux_1_1_x86_64.whl (425 kB)
  Installing collected packages: patchelf
  Successfully installed patchelf-0.17.2.1
  Installing backend dependencies ... done
  Running command Preparing metadata (pyproject.toml)
  + meson setup /home/miroi/work/software/xtb-python /home/miroi/work/software/xtb-python/.mesonpy-0zcpvm6q -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/home/miroi/work/software/xtb-python/.mesonpy-0zcpvm6q/meson-python-native-file.ini
  The Meson build system
  Version: 1.6.0
  Source dir: /home/miroi/work/software/xtb-python
  Build dir: /home/miroi/work/software/xtb-python/.mesonpy-0zcpvm6q
  Build type: native build
  Project name: xtb-python
  Project version: undefined
  C compiler for the host machine: cc (gcc 11.4.0 "cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
  C linker for the host machine: cc ld.bfd 2.38
  Host machine cpu family: x86_64
  Host machine cpu: x86_64
  Found pkg-config: YES (/usr/bin/pkg-config) 0.29.2
  Found CMake: /usr/bin/cmake (3.22.1)
  Run-time dependency xtb found: NO (tried pkgconfig and cmake)
  Looking for a fallback subproject for the dependency xtb

  Executing subproject xtb-6.5.1

  xtb-6.5.1| Project name: xtb
  xtb-6.5.1| Project version: 6.5.1
  xtb-6.5.1| Fortran compiler for the host machine: gfortran (gcc 11.4.0 "GNU Fortran (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
  xtb-6.5.1| Fortran linker for the host machine: gfortran ld.bfd 2.38
  xtb-6.5.1| C compiler for the host machine: cc (gcc 11.4.0 "cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
  xtb-6.5.1| C linker for the host machine: cc ld.bfd 2.38
  xtb-6.5.1| Program git found: YES (/usr/bin/git)
  xtb-6.5.1| WARNING: You should add the boolean check kwarg to the run_command call.
  xtb-6.5.1| It currently defaults to false,
  xtb-6.5.1| but it will default to true in meson 2.0.
  xtb-6.5.1| See also: https://github.com/mesonbuild/meson/issues/9300
  xtb-6.5.1| Program python3 found: YES (/usr/bin/python3)
  xtb-6.5.1| Configuring xtb_version.fh using configuration
  xtb-6.5.1| Library mkl_gf_lp64 found: YES
  xtb-6.5.1| Library mkl_gnu_thread found: YES
  xtb-6.5.1| Library mkl_core found: YES
  xtb-6.5.1| Run-time dependency OpenMP found: YES 4.5
  xtb-6.5.1| Run-time dependency threads found: YES
  xtb-6.5.1| Run-time dependency mctc-lib found: NO (tried pkgconfig and cmake)
  xtb-6.5.1| Looking for a fallback subproject for the dependency mctc-lib
  xtb-6.5.1| Using subprojects/xtb-6.5.1/subprojects/mctc-lib.wrap

  Executing subproject xtb-6.5.1:mctc-lib

  mctc-lib| Project name: mctc-lib
  mctc-lib| Project version: 0.3.0
  mctc-lib| Fortran compiler for the host machine: gfortran (gcc 11.4.0 "GNU Fortran (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
  mctc-lib| Fortran linker for the host machine: gfortran ld.bfd 2.38
  mctc-lib| Run-time dependency json-fortran found: NO (tried pkgconfig and cmake)
  mctc-lib| Looking for a fallback subproject for the dependency json-fortran
  mctc-lib| Building fallback subproject with default_library=static

  Executing subproject xtb-6.5.1:mctc-lib:json-fortran-8.2.5

  json-fortran-8.2.5| Project name: jsonfortran
  json-fortran-8.2.5| Project version: 8.2.5
  json-fortran-8.2.5| Fortran compiler for the host machine: gfortran (gcc 11.4.0 "GNU Fortran (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
  json-fortran-8.2.5| Fortran linker for the host machine: gfortran ld.bfd 2.38
  json-fortran-8.2.5| Build targets in project: 1
  json-fortran-8.2.5| Subproject json-fortran-8.2.5 finished.

  mctc-lib| Dependency json-fortran from subproject subprojects/xtb-6.5.1/subprojects/json-fortran-8.2.5 found: YES 8.2.5
  mctc-lib| Build targets in project: 4
  mctc-lib| Subproject mctc-lib finished.

  xtb-6.5.1| Dependency mctc-lib from subproject subprojects/xtb-6.5.1/subprojects/mctc-lib found: YES 0.3.0
  xtb-6.5.1| Program asciidoctor found: NO
  xtb-6.5.1| Run-time dependency test-drive found: NO (tried pkgconfig and cmake)
  xtb-6.5.1| Looking for a fallback subproject for the dependency test-drive
  xtb-6.5.1| Using subprojects/xtb-6.5.1/subprojects/test-drive.wrap

  Executing subproject xtb-6.5.1:test-drive

  test-drive| Project name: test-drive
  test-drive| Project version: 0.3.0
  test-drive| Fortran compiler for the host machine: gfortran (gcc 11.4.0 "GNU Fortran (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
  test-drive| Fortran linker for the host machine: gfortran ld.bfd 2.38
  test-drive| Build targets in project: 9
  test-drive| Subproject test-drive finished.

  xtb-6.5.1| Dependency test-drive from subproject subprojects/xtb-6.5.1/subprojects/test-drive found: YES 0.3.0
  xtb-6.5.1| Build targets in project: 10
  xtb-6.5.1| Subproject xtb-6.5.1 finished.

  Dependency xtb from subproject subprojects/xtb-6.5.1 found: YES 6.5.1
  Program python3 (cffi) found: YES (/usr/bin/python3) modules: cffi
  Run-time dependency python found: YES 3.10
  Configuring _libxtb.h with command
  Configuring _libxtb.c with command

  ../meson.build:77:16: ERROR: Command `/usr/bin/python3 /home/miroi/work/software/xtb-python/ffibuilder.py /home/miroi/work/software/xtb-python/.mesonpy-0zcpvm6q/_libxtb.h _libxtb` failed with status 1.

  A full log can be found at /home/miroi/work/software/xtb-python/.mesonpy-0zcpvm6q/meson-logs/meson-log.txt
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /usr/bin/python3 /usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpycd3a_4r
  cwd: /home/miroi/work/software/xtb-python
  Preparing metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
~~~

**Comment by awvwgk** [comment]
It would be great to see the output in `meson-log.txt`

**Comment by miroi** [comment]
> It would be great to see the output in `meson-log.txt`

The problem that there is not xtb-python/.mesonpy-gnj5iqa9/meson-logs/meson-log.txt file. 

I see only two empty .mesonpy-* directories.  Where can I find the meson-log.txt text file please ?

**Comment by miroi** [comment]
> It would be great to see the output in `meson-log.txt`

Buildup once again:
~~~
miroi@MIRO:~/work/software/xtb-python/.xtb --version
      -----------------------------------------------------------
     |                   =====================                   |
     |                           x T B                           |
     |                   =====================                   |
     |                         S. Grimme                         |
     |          Mulliken Center for Theoretical Chemistry        |
     |                    University of Bonn                     |
      -----------------------------------------------------------

   * xtb version 6.7.1 (edcfbbe) compiled by 'albert@albert-system' on 2024-07-22

normal termination of xtb
miroi@MIRO:~/work/software/xtb-python/.pip3 install -v -v -v .
Using pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)
Defaulting to user installation because normal site-packages is not writeable
Created temporary directory: /tmp/pip-ephem-wheel-cache-tdqc9kwb
Created temporary directory: /tmp/pip-req-tracker-od88fbpj
Initialized build tracking at /tmp/pip-req-tracker-od88fbpj
Created build tracker: /tmp/pip-req-tracker-od88fbpj
Entered build tracker: /tmp/pip-req-tracker-od88fbpj
Created temporary directory: /tmp/pip-install-v9c095rd
Processing /home/miroi/work/software/xtb-python
  Added file:///home/miroi/work/software/xtb-python to build tracker '/tmp/pip-req-tracker-od88fbpj'
  Created temporary directory: /tmp/pip-build-env-evyi0_t6
  Created temporary directory: /tmp/pip-standalone-pip-p6xf9w81
  Running command pip subprocess to install build dependencies
  Using pip 22.0.2 from /tmp/pip-standalone-pip-p6xf9w81/__env_pip__.zip/pip (python 3.10)
  Collecting meson-python
    Using cached meson_python-0.17.1-py3-none-any.whl (27 kB)
  Collecting cffi
    Using cached cffi-1.17.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (446 kB)
  Collecting tomli>=1.0.0
    Using cached tomli-2.1.0-py3-none-any.whl (13 kB)
  Collecting meson>=0.63.3
    Using cached meson-1.6.0-py3-none-any.whl (973 kB)
  Collecting pyproject-metadata>=0.7.1
    Using cached pyproject_metadata-0.9.0-py3-none-any.whl (18 kB)
  Collecting packaging>=19.0
    Using cached packaging-24.2-py3-none-any.whl (65 kB)
  Collecting pycparser
    Using cached pycparser-2.22-py3-none-any.whl (117 kB)
  Installing collected packages: tomli, pycparser, packaging, meson, pyproject-metadata, cffi, meson-python
    Creating /tmp/pip-build-env-evyi0_t6/overlay/local/bin
    changing mode of /tmp/pip-build-env-evyi0_t6/overlay/local/bin/meson to 755
  Successfully installed cffi-1.17.1 meson-1.6.0 meson-python-0.17.1 packaging-24.2 pycparser-2.22 pyproject-metadata-0.9.0 tomli-2.1.0
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  Getting requirements to build wheel ... done
  Created temporary directory: /tmp/pip-modern-metadata-8_3dxfw4
  Running command Preparing metadata (pyproject.toml)
  + meson setup /home/miroi/work/software/xtb-python /home/miroi/work/software/xtb-python/.mesonpy-twva4526 -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/home/miroi/work/software/xtb-python/.mesonpy-twva4526/meson-python-native-file.ini
  The Meson build system
  Version: 1.6.0
  Source dir: /home/miroi/work/software/xtb-python
  Build dir: /home/miroi/work/software/xtb-python/.mesonpy-twva4526
  Build type: native build
  Project name: xtb-python
  Project version: undefined
  C compiler for the host machine: cc (gcc 11.4.0 "cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
  C linker for the host machine: cc ld.bfd 2.38
  Host machine cpu family: x86_64
  Host machine cpu: x86_64
  Found pkg-config: YES (/usr/bin/pkg-config) 0.29.2
  Run-time dependency xtb found: YES 6.7.1
  Program python3 (cffi) found: YES (/usr/bin/python3) modules: cffi
  Run-time dependency python found: YES 3.10
  Configuring _libxtb.h with command
  Configuring _libxtb.c with command

  ../meson.build:77:16: ERROR: Command `/usr/bin/python3 /home/miroi/work/software/xtb-python/ffibuilder.py /home/miroi/work/software/xtb-python/.mesonpy-twva4526/_libxtb.h _libxtb` failed with status 1.

  A full log can be found at /home/miroi/work/software/xtb-python/.mesonpy-twva4526/meson-logs/meson-log.txt
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /usr/bin/python3 /usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpq9stes0p
  cwd: /home/miroi/work/software/xtb-python
  Preparing metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/build/metadata.py", line 35, in generate_metadata
    distinfo_dir = backend.prepare_metadata_for_build_wheel(metadata_dir)
  File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/wrappers.py", line 188, in prepare_metadata_for_build_wheel
    return self._call_hook('prepare_metadata_for_build_wheel', {
  File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/wrappers.py", line 322, in _call_hook
    self._subprocess_runner(
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/subprocess.py", line 252, in runner
    call_subprocess(
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/subprocess.py", line 224, in call_subprocess
    raise error
pip._internal.exceptions.InstallationSubprocessError: Preparing metadata (pyproject.toml) exited with 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 165, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 339, in run
    requirement_set = resolver.resolve(
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 75, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/factory.py", line 506, in collect_root_requirements
    req = self._make_requirement_from_install_req(
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/factory.py", line 468, in _make_requirement_from_install_req
    cand = self._make_candidate_from_link(
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/factory.py", line 215, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 288, in __init__
    super().__init__(
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 158, in __init__
    self.dist = self._prepare()
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 227, in _prepare
    dist = self._prepare_distribution()
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 299, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 487, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 556, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 58, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/usr/lib/python3/dist-packages/pip/_internal/distributions/sdist.py", line 47, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/usr/lib/python3/dist-packages/pip/_internal/req/req_install.py", line 522, in prepare_metadata
    self.metadata_directory = generate_metadata(
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/build/metadata.py", line 37, in generate_metadata
    raise MetadataGenerationFailed(package_details=details) from error
pip._internal.exceptions.MetadataGenerationFailed: metadata generation failed
Removed file:///home/miroi/work/software/xtb-python from build tracker '/tmp/pip-req-tracker-od88fbpj'
Removed build tracker: '/tmp/pip-req-tracker-od88fbpj'
~~~

**Comment by awvwgk** [comment]
You can use `--config-settings=build-dir=_build` to retain the build directory and inspect the intermediate outputs.

**Comment by miroi** [comment]
Thanks for your help, I updated pip.

I see combination of GNU compiler with intel-mkl library... how to overcome this issue ?

Also - I downloaded xtb from https://github.com/grimme-lab/xtb/releases/tag/v6.7.1 and provided envirovariables, why is it building xtb lower version ?


~~~
pip wheel --config-settings="build-dir=_build" install  .
.
.
.
      FAILED: subprojects/xtb-6.5.1/test/api/xtb_c_test
      cc  -o subprojects/xtb-6.5.1/test/api/xtb_c_test subprojects/xtb-6.5.1/test/api/xtb_c_test.p/c_api_example.c.o -L/usr/lib/gcc/x86_64-linux-gnu/11 -L/usr/lib/x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu -L/usr/lib -L/usr/lib/gcc/x86_64-linux-gnu/11/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/11/../../.. -L/lib -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -static -Wl,--start-group subprojects/xtb-6.5.1/libxtb.a subprojects/xtb-6.5.1/subprojects/mctc-lib/libmctc-lib.a subprojects/xtb-6.5.1/subprojects/json-fortran-8.2.5/libjsonfortran.a -lmkl_gf_lp64 -lmkl_gnu_thread -lmkl_core -fopenmp -pthread -lmkl_gf_lp64 -lmkl_gnu_thread -lmkl_core -fopenmp -lgfortran -lm -Wl,--end-group
      /usr/bin/ld: /usr/lib/x86_64-linux-gnu/libmkl_core.a(mkl_semaphore.o): in function `mkl_serv_inspector_suppress':
      mkl_semaphore.c:(.text+0xb9): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
      /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/libgfortran.a(write.o): in function `determine_en_precision':
      (.text.determine_en_precision+0x1cc): undefined reference to `quadmath_snprintf'
      /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/libgfortran.a(write.o): in function `get_float_string':
      (.text.get_float_string+0x216): undefined reference to `quadmath_snprintf'
      /usr/bin/ld: (.text.get_float_string+0xecf): undefined reference to `quadmath_snprintf'
      /usr/bin/ld: (.text.get_float_string+0x16ac): undefined reference to `quadmath_snprintf'
      /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/libgfortran.a(ieee_arithmetic.o): in function `__ieee_arithmetic_MOD_ieee_value_16':
      (.text+0x516): undefined reference to `sqrtq'
      collect2: error: ld returned 1 exit status
      ninja: build stopped: subcommand failed.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
~~~

**Comment by awvwgk** [comment]
There seems to be some issue with your build environment, it seems to be unstable regarding what version of xtb can be found or which compiler is used, making it hard to draw conclusions. I have seen now several different errors which all might have very different causes.

The latest error originates from building xtb itself and failing due to missing system libraries for Fortran.

If you are only looking for xtb-python with mkl support I recommend to use mamba to install the distribution from conda-forge (you can get mamba from [here](https://github.com/conda-forge/miniforge)):

````
mamba install xtb-python 'liblapack=*=*mkl*'
````

For building xtb-python from source, please make yourself familiar with building xtb first. If you want to use the statically linked distribution from the release page, you need to keep in mind that only the executable is statically linked, but the provided archive still depends on the Intel libraries, so for linking you would need the Intel compiler libraries as well.

**Comment by awvwgk** [comment]
Closing this as resolved. Feel free to open a new issue in case there are more questions or issues.
