### ISSUE TITLE
Installing with Conda isn't working

### ISSUE THREAD

**Issue by civanescu** [grimme-lab/xtb-python#93]
I'm trying to create a docker machine expecially for developing app for xtb. 
But when I try to `from xtb.libxtb import VERBOSITY_FULL` I have error `ImportError: xtb C extension unimportable, cannot use C-API`

I tried to use python 3.8 (because it seems the code it is 3.8), conda. So I followed the conda install recomandation.

#### My actual config is:
Dockerfile
```
FROM buildpack-deps:bullseye

[...]

RUN conda install -y -c anaconda python=3.8 \
    && conda config --add channels conda-forge \
    && conda install -y -c conda-forge xtb-python qcelemental ase

[...]
```

Full error:
```
Python 3.8.15 (default, Nov 24 2022, 15:19:38) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from xtb.libxtb import VERBOSITY_FULL
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/xtb/libxtb.py", line 32, in <module>
    from ._libxtb import ffi, lib
ImportError: /opt/conda/lib/python3.8/site-packages/_cffi_backend.cpython-38-x86_64-linux-gnu.so: undefined symbol: ffi_type_uint32, version LIBFFI_BASE_7.0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/xtb/libxtb.py", line 34, in <module>
    raise ImportError("xtb C extension unimportable, cannot use C-API")
ImportError: xtb C extension unimportable, cannot use C-API
>>>
```

**Comment by civanescu** [comment]
solved by adding cffi in packages
